[changelog]
header = """
# Changelog\n
"""
body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [unreleased]
{% endif %}\
{% for scope, scope_commits in commits | group_by(attribute="scope") %}
    {% if scope %}
    ### {{ scope | upper_first }}
    {% else %}
    ### Core
    {% endif %}
    {% for group, commits in scope_commits | group_by(attribute="group") %}
        #### {{ group | upper_first }}
        {% for commit in commits %}
            - {{ commit.message | upper_first }}\
        {% endfor %}
    {% endfor %}
{% endfor %}\n
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true # ignore commits without "prefix:"
split_commits = false
commit_preprocessors = [
    { pattern = '\((\w+\s)?#([0-9]+)\)', replace = ""},
]
commit_parsers = [
    { message = "^feat", group = "Features"},
    { message = "^fix", group = "Bug Fixes"},
    { message = "^refactor", group = "Refactor"},
    { message = "^chore", group = "Chores"},
    { message = "^doc", group = "Documentation"},
    { message = "^perf", group = "Performance"},
    { message = "^style", group = "Styling"},
    { message = "^security", group = "Security"},
    { body = ".*security", group = "Security"},
]
protect_breaking_commits = false
filter_commits = true # ignore prefixes not listed above
tag_pattern = "v[0-9]*"
skip_tags = "v[0-9]*-.*" # ignore pre-release semver tags
ignore_tags = ""
topo_order = false
sort_commits = "oldest"
