[application]
name = "markdown-neuraxis"
default_platform = "desktop"
asset_dir = "crates/markdown-neuraxis-dioxus/src/assets"

[application.tools]
out_dir = "dist"

[bundle]
identifier = "co.rustworkshop.markdown_neuraxis"
publisher = "tim-abell"

[web.app]
title = "markdown-neuraxis"

[web.watcher]
watch_path = ["src", "assets"]

[desktop.app]
window.title = "markdown-neuraxis"
window.width = 1200
window.height = 800
window.resizable = true